export interface HeroImage {
  src: string;
  alt: string;
}

const alts = [
  "Professional removal team loading furniture in Glasgow",
  "MA Removals van ready for a house move in Edinburgh",
  "Careful handling of household items during a move",
  "Experienced movers carrying furniture through a doorway",
  "Fully loaded removal van on a Scottish street",
  "Professional packing service for a home relocation",
  "MA Removals team completing an office move in Dundee",
  "Safe and insured furniture transport across Scotland",
  "Friendly removal crew helping with a flat move",
  "Piano being carefully moved by specialist removers",
  "Removal team navigating narrow stairs with wardrobe",
  "Clean and organized removal van interior",
  "Customer handshake after a successful house move",
  "Loading boxes and furniture for a business relocation",
  "MA Removals van driving through Scottish countryside",
] as const;

// Cycle through alt texts by index
const a = (i: number): string => alts[i % alts.length] as string;

export const heroImages: HeroImage[] = [
  { src: "/images/hero/hero-01.jpg", alt: a(0) },
  { src: "/images/hero/hero-02.jpg", alt: a(1) },
  { src: "/images/hero/hero-03.jpg", alt: a(2) },
  { src: "/images/hero/hero-04.jpg", alt: a(3) },
  { src: "/images/hero/hero-05.jpg", alt: a(4) },
  { src: "/images/hero/hero-06.jpg", alt: a(5) },
  { src: "/images/hero/hero-07.jpg", alt: a(6) },
  { src: "/images/hero/hero-08.jpg", alt: a(7) },
  { src: "/images/hero/hero-09.jpg", alt: a(8) },
  { src: "/images/hero/hero-10.jpg", alt: a(9) },
  { src: "/images/hero/hero-11.jpg", alt: a(10) },
  { src: "/images/hero/hero-12.jpg", alt: a(11) },
  { src: "/images/hero/hero-13.jpg", alt: a(12) },
  { src: "/images/hero/hero-14.jpg", alt: a(13) },
  { src: "/images/hero/hero-15.jpg", alt: a(14) },
  { src: "/images/hero/hero-16.jpg", alt: a(0) },
  { src: "/images/hero/hero-17.jpg", alt: a(1) },
  { src: "/images/hero/hero-18.jpg", alt: a(2) },
  { src: "/images/hero/hero-19.jpg", alt: a(3) },
  { src: "/images/hero/hero-20.jpg", alt: a(4) },
  { src: "/images/hero/hero-21.jpg", alt: a(5) },
  { src: "/images/hero/hero-22.jpg", alt: a(6) },
  { src: "/images/hero/hero-23.jpg", alt: a(7) },
  { src: "/images/hero/hero-24.jpg", alt: a(8) },
  { src: "/images/hero/hero-25.jpg", alt: a(9) },
  { src: "/images/hero/hero-26.jpg", alt: a(10) },
  { src: "/images/hero/hero-27.jpg", alt: a(11) },
  { src: "/images/hero/hero-28.jpg", alt: a(12) },
  { src: "/images/hero/hero-29.jpg", alt: a(13) },
  { src: "/images/hero/hero-30.jpg", alt: a(14) },
  { src: "/images/hero/hero-31.jpg", alt: a(0) },
  { src: "/images/hero/hero-32.jpg", alt: a(1) },
  { src: "/images/hero/hero-33.jpg", alt: a(2) },
  { src: "/images/hero/hero-34.jpg", alt: a(3) },
  { src: "/images/hero/hero-35.jpg", alt: a(4) },
  { src: "/images/hero/hero-36.jpg", alt: a(5) },
  { src: "/images/hero/hero-37.jpg", alt: a(6) },
  { src: "/images/hero/hero-38.jpg", alt: a(7) },
  { src: "/images/hero/hero-39.jpg", alt: a(8) },
  { src: "/images/hero/hero-40.jpg", alt: a(9) },
  { src: "/images/hero/hero-41.jpg", alt: a(10) },
  { src: "/images/hero/hero-42.jpg", alt: a(11) },
  { src: "/images/hero/hero-43.jpg", alt: a(12) },
  { src: "/images/hero/hero-44.jpg", alt: a(13) },
  { src: "/images/hero/hero-45.jpg", alt: a(14) },
  { src: "/images/hero/hero-46.jpg", alt: a(0) },
  { src: "/images/hero/hero-47.jpg", alt: a(1) },
];
